src/sbadmin/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls import include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),

    # Index
    re_path(r'^$', views.IndexView.as_view(), name="index_url"),

    path('users/', include('users.urls', namespace="users")),
]

src/tradeflowsystem/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls import include
from users.views import LoginView

urlpatterns = [
    path('admin/', admin.site.urls),

    # Login
    re_path(r'^$', LoginView.as_view(), name="login_url"),

    path('users/', include('users.urls', namespace="users")),
]

src/users/urls.py
from django.urls import re_path, path 
from . import views

app_name = "users"


urlpatterns = [
   	# Login, Register, Forgot password, Logout
    re_path(r'^login/$', views.LoginView.as_view(), name="login_url"),
    re_path(r'^register/$', views.RegisterView.as_view(), name="register_url"),
    re_path(r'^forgot-password/$', views.ForgotPasswordView.as_view(), name="forgot_password_url"),
    re_path(r'^logout/$', views.LogoutView.as_view(), name="logout_url"),

    re_path(r'^charts/$', views.ChartsView.as_view(), name="charts_url"),

    re_path(r'^tables/$', views.TablesView.as_view(), name="tables_url"),

    re_path(r'^buttons/$', views.ButtonsView.as_view(), name="buttons_url"),

    re_path(r'^cards/$', views.CardsView.as_view(), name="cards_url"),

	re_path(r'^page_not_found/$', views.PageNotFoundView.as_view(), name="page_not_found_url"),    

	re_path(r'^blank/$', views.BlankView.as_view(), name="blank_page_url"),    

	# Utilities
	re_path(r'^colors/$', views.ColorsView.as_view(), name="colors_url"),    

	re_path(r'^borders/$', views.BordersView.as_view(), name="borders_url"),    

	re_path(r'^animations/$', views.AnimationsView.as_view(), name="animations_url"),    

	re_path(r'^others/$', views.OthersView.as_view(), name="others_url"),    

]

src/users/models.py
from django.db import models

# Create your models here.

src/sbadmin/views.py
from django.shortcuts import render
from rest_framework.views import APIView
from rest_framework.response import Response


class IndexView(APIView):
	def get(self, request, *args, **kwargs):
		return render(request, "theme/index.html", {})

	def post(self, request, *args, **kwargs):

		return Response({'status': 200})

src/users/views.py
from django.shortcuts import render
from rest_framework.views import APIView
from rest_framework.response import Response


class LoginView(APIView):
    def get(self, request, *args, **kwargs):
        return render(request, "theme/login.html", {})

    def post(self, request, *args, **kwargs):

        return Response({'status': 200})


class RegisterView(APIView):
    def get(self, request, *args, **kwargs):
        return render(request, "theme/register.html", {})

    def post(self, request, *args, **kwargs):

        return Response({'status': 200})


class ForgotPasswordView(APIView):
    def get(self, request, *args, **kwargs):
        return render(request, "theme/forgot-password.html", {})

    def post(self, request, *args, **kwargs):

        return Response({'status': 200})


class LogoutView(APIView):
    def get(self, request, *args, **kwargs):
        return render(request, "theme/forgot-password.html", {})

    def post(self, request, *args, **kwargs):

        return Response({'status': 200})


class ChartsView(APIView):
    def get(self, request, *args, **kwargs):
        return render(request, "theme/charts.html", {})

    def post(self, request, *args, **kwargs):

        return Response({'status': 200})


class TablesView(APIView):
    def get(self, request, *args, **kwargs):
        return render(request, "theme/tables.html", {})

    def post(self, request, *args, **kwargs):

        return Response({'status': 200})


class LogoutView(APIView):
    def get(self, request, *args, **kwargs):
        return render(request, "theme/forgot-password.html", {})

    def post(self, request, *args, **kwargs):

        return Response({'status': 200})


class ButtonsView(APIView):
    def get(self, request, *args, **kwargs):
        return render(request, "theme/buttons.html", {})

    def post(self, request, *args, **kwargs):

        return Response({'status': 200})


class CardsView(APIView):
    def get(self, request, *args, **kwargs):
        return render(request, "theme/cards.html", {})

    def post(self, request, *args, **kwargs):

        return Response({'status': 200})


class PageNotFoundView(APIView):
    def get(self, request, *args, **kwargs):
        return render(request, "theme/404.html", {})

    def post(self, request, *args, **kwargs):

        return Response({'status': 200})


class BlankView(APIView):
    def get(self, request, *args, **kwargs):
        return render(request, "theme/blank.html", {})

    def post(self, request, *args, **kwargs):

        return Response({'status': 200})


class ColorsView(APIView):
    def get(self, request, *args, **kwargs):
        return render(request, "theme/utilities-color.html", {})

    def post(self, request, *args, **kwargs):

        return Response({'status': 200})


class BordersView(APIView):
    def get(self, request, *args, **kwargs):
        return render(request, "theme/utilities-border.html", {})

    def post(self, request, *args, **kwargs):

        return Response({'status': 200})


class AnimationsView(APIView):
    def get(self, request, *args, **kwargs):
        return render(request, "theme/utilities-animation.html", {})

    def post(self, request, *args, **kwargs):

        return Response({'status': 200})


class OthersView(APIView):
    def get(self, request, *args, **kwargs):
        return render(request, "theme/utilities-other.html", {})

    def post(self, request, *args, **kwargs):

        return Response({'status': 200})



class DashboardView(APIView):
    def get(self, request, *args, **kwargs):
        return render(request, "users/dashboard.html", {})

    def post(self, request, *args, **kwargs):

        return Response({'status': 200})

src/ui/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>{{WEBSITE_FOOTER_NAME}} - {% block title %} {% endblock %}</title>

        <!-- Custom fonts for this template-->
        <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
        <!-- Custom styles for this template-->
        <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

        {% block css %}
        {% endblock %}

        {% block js_head %}
        {% endblock %}
    </head>
    <body id="page-top">
        <!-- Page Wrapper -->
        <div id="wrapper">
            <!-- Sidebar -->
            {% include 'theme/components/sidebar.html' %}
            <!-- End of Sidebar -->
            <!-- Content Wrapper -->
            <div id="content-wrapper" class="d-flex flex-column">
                <!-- Main Content -->
                <div id="content">
                    <!-- Topbar -->
                    {% include 'theme/components/navbar.html' %}
                    <!-- End of Topbar -->

                    <!-- Begin Page Content -->
                    {% block container_fluid %}

                    {% endblock %}
                    <!-- /.container-fluid -->
                </div>
                <!-- End of Main Content -->
                <!-- Footer -->
                <footer class="sticky-footer bg-white">
                    <div class="container my-auto">
                        <div class="copyright text-center my-auto">
                            <span>Copyright &copy; {{WEBSITE_FOOTER_NAME}} {{CURRENT_YEAR}}</span>
                        </div>
                    </div>
                </footer>
                <!-- End of Footer -->
            </div>
            <!-- End of Content Wrapper -->
        </div>
        <!-- End of Page Wrapper -->
        <!-- Scroll to Top Button-->
        <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
        </a>
        <!-- Logout Modal-->
        <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                        </button>
                    </div>
                    <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                    <div class="modal-footer">
                        <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                        <a class="btn btn-primary" href="{% url 'users:login_url' %}">Logout</a>
                    </div>
                </div>
            </div>
        </div>
        <!-- Bootstrap core JavaScript-->
        <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
        <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
        <!-- Core plugin JavaScript-->
        <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>
        <!-- Custom scripts for all pages-->
        <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

        <!-- Page level plugins -->
        <script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>
        <!-- Page level custom scripts -->
        <script src="{% static 'js/demo/chart-area-demo.js' %}"></script>
        <script src="{% static 'js/demo/chart-pie-demo.js' %}"></script>

        <!-- Page level custom scripts (Only for charts page) -->
        <script src="{% static 'js/demo/chart-bar-demo.js' %}"></script>

        {% block js_body %}

        {% endblock %}
    </body>
</html>

src/ui/templates/base_x.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>{{WEBSITE_FOOTER_NAME}} - {% block title %} {% endblock %}</title>

  <!-- Custom fonts for this template-->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

  <!--Added-->
  <link rel="stylesheet" type="text/css" href="{% static 'resource/css/base_x.css' %}">

  {% block css %}
  {% endblock %}

  {% block js_head %}
  {% endblock %}
</head>

<body> <!-- class="bg-gradient-primary" -->
  {% include 'theme/components/navbar_x.html' %}


  {% block container %}
  {% endblock %}

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'js/sb-admin-2.min.js' %}"></script>
  <script type="text/javascript">
    $(document).ready(function() {
        $('.data-top-right-link').click(function() {
            let next_location = $(this).find('a').attr('href')
            location.href = next_location
        })
    })
  </script>
  {% block js_body %}
  {% endblock %}
</body>

</html>

src/ui/templates/theme/blank.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Blank {% endblock %}

{% block container_fluid %}
<div class="container-fluid">

	<!-- Page Heading -->
	<h1 class="h3 mb-4 text-gray-800">Blank Page</h1>

</div>
{% endblock %}

src/ui/templates/theme/components/charts_scripts.html
{% load static %}
<!-- Page level plugins -->
<script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>
<!-- Page level custom scripts -->
<script src="{% static 'js/demo/chart-area-demo.js' %}"></script>
<script src="{% static 'js/demo/chart-pie-demo.js' %}"></script>

src/ui/templates/theme/components/navbar_x.html
{% load static %}

<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
    <div class="d-none d-sm-inline-block mr-auto ml-md-3 my-2 my-md-0 mw-100">
        <img class="img-responsive" src="{% static 'resource/logos/hygull_bg_1a1b1a.png' %}" id='site-logo-x'>
    </div>

    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">
        <!-- Nav Item - Alerts -->
        <li class="nav-item dropdown no-arrow mx-1 data-top-right-link login-top-right-link">
            <a class="nav-link dropdown-toggle" href="{% url 'users:login_url' %}" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span>Login</span>
                <!-- Counter - Alerts -->
                <span class="badge badge-danger badge-counter">
                    <i class="fas fa-sign-in-alt fa-fw"></i>
                </span>
            </a>
        </li>

        <li class="nav-item dropdown no-arrow mx-1 data-top-right-link register-top-right-link">
            <a class="nav-link dropdown-toggle" href="{% url 'users:register_url' %}" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span>Register</span>

                <!-- Counter - Alerts -->
                <span class="badge badge-danger badge-counter">
                    <i class="fas fa-user-plus fa-fw"></i>
                </span>
            </a>
        </li>
    </ul>
</nav>

src/ui/templates/theme/components/sidebar.html
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'index_url' %}">
        <div class="sidebar-brand-icon rotate-n-15">
          <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3"> {{WEBSITE_TOP_LEFT_NAME}}<sup>x</sup></div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Dashboard -->
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'index_url' %}">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Dashboard</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        Interface
      </div>

      <!-- Nav Item - Pages Collapse Menu -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
          <i class="fas fa-fw fa-cog"></i>
          <span>Components</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Custom Components:</h6>
            <a class="collapse-item" href="{% url 'users:buttons_url' %}">Buttons</a>
            <a class="collapse-item" href="{% url 'users:cards_url' %}">Cards</a>
          </div>
        </div>
      </li>

      <!-- Nav Item - Utilities Collapse Menu -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities" aria-expanded="true" aria-controls="collapseUtilities">
          <i class="fas fa-fw fa-wrench"></i>
          <span>Utilities</span>
        </a>
        <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Custom Utilities:</h6>
            <a class="collapse-item" href="{% url 'users:colors_url' %}">Colors</a>
            <a class="collapse-item" href="{% url 'users:borders_url' %}">Borders</a>
            <a class="collapse-item" href="{% url 'users:animations_url' %}">Animations</a>
            <a class="collapse-item" href="{% url 'users:others_url' %}">Other</a>
          </div>
        </div>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        Addons
      </div>

      <!-- Nav Item - Pages Collapse Menu -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true" aria-controls="collapsePages">
          <i class="fas fa-fw fa-folder"></i>
          <span>Pages</span>
        </a>
        <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Login Screens:</h6>
            <a class="collapse-item" href="{% url 'users:login_url' %}">Login</a>
            <a class="collapse-item" href="{% url 'users:register_url' %}">Register</a>
            <a class="collapse-item" href="{% url 'users:forgot_password_url' %}">Forgot Password</a>
            <div class="collapse-divider"></div>
            <h6 class="collapse-header">Other Pages:</h6>
            <a class="collapse-item" href="{% url 'users:page_not_found_url' %}">404 Page</a>
            <a class="collapse-item" href="{% url 'users:blank_page_url' %}">Blank Page</a>
          </div>
        </div>
      </li>

      <!-- Nav Item - Charts -->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'users:charts_url' %}">
          <i class="fas fa-fw fa-chart-area"></i>
          <span>Charts</span></a>
      </li>

      <!-- Nav Item - Tables -->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'users:tables_url' %}">
          <i class="fas fa-fw fa-table"></i>
          <span>Tables</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block">

      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>

src/ui/templates/theme/forgot-password.html
{% extends 'base_x.html' %}
{% load static %}


{% block title %} Forgot password {% endblock %}


{% block container %}
<div class="container">
    <!-- Outer Row -->
    <div class="row justify-content-center">
        <div class="col-xl-10 col-lg-12 col-md-9">
            <div class="card o-hidden border-0 shadow-lg my-5">
                <div class="card-body p-0">
                    <!-- Nested Row within Card Body -->
                    <div class="row">
                        <!--
                            <div class="col-lg-6 d-none d-lg-block bg-password-image"></div>
                            -->
                        <div class="col-lg-8 offset-lg-2">
                            <div class="p-5">
                                <div class="text-center">
                                    <h1 class="h4 text-gray-900 mb-2">Forgot Your Password?</h1>
                                    <p class="mb-4">We get it, stuff happens. Just enter your email address below and we'll send you a link to reset your password!</p>
                                </div>
                                <form class="user">
                                    <div class="form-group">
                                        <label for="email">Email Address</label>
                                        <input type="email" class="form-control form-control-user" id="email" aria-describedby="emailHelp" placeholder="Enter Email Address...">
                                    </div>
                                    <a href="{% url 'users:login_url' %}" class="btn btn-primary btn-user btn-block">
                                    Reset Password
                                    </a>
                                </form>
                                <hr>
                                <div class="text-center">
                                    <a class="small" href="{% url 'users:register_url' %}">Create an Account!</a>
                                </div>
                                <div class="text-center">
                                    <a class="small" href="{% url 'users:login_url' %}">Already have an account? Login!</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

src/ui/templates/theme/login.html
{% extends 'base_x.html' %}
{% load static %}

{% block title %} Login {% endblock %}

{% block container %}

<div class="container">
    <!-- Outer Row -->
    <div class="row justify-content-center">
        <div class="col-xl-10 col-lg-12 col-md-9">
            <div class="card o-hidden border-0 shadow-lg my-5">
                <div class="card-body p-0">
                    <!-- Nested Row within Card Body -->
                    <div class="row">
                        <!--
                          <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                        -->
                        <div class="col-lg-8 offset-lg-2">
                            <div class="p-5">
                                <div class="text-center">
                                    <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                                </div>
                                <form class="user">
                                    <div class="form-group">
                                        <label for="email">Email</label>
                                        <input type="email" class="form-control form-control-user" id="email" aria-describedby="emailHelp" placeholder="Enter Email Address...">
                                    </div>
                                    <div class="form-group">
                                        <label for="password">Password</label>
                                        <input type="password" class="form-control form-control-user" id="password" placeholder="Password">
                                    </div>
                                    <div class="form-group">
                                        <div class="custom-control custom-checkbox small">
                                            <input type="checkbox" class="custom-control-input" id="customCheck">
                                            <label class="custom-control-label" for="customCheck">Remember Me</label>
                                        </div>
                                    </div>
                                    <a href="{% url 'index_url' %}" class="btn btn-primary btn-user btn-block">
                                      Login
                                    </a>
                                    <hr>
                                    <a href="{% url 'index_url' %}" class="btn btn-google btn-user btn-block">
                                    <i class="fab fa-google fa-fw"></i> Login with Google
                                    </a>
                                    <a href="{% url 'index_url' %}" class="btn btn-facebook btn-user btn-block">
                                    <i class="fab fa-facebook-f fa-fw"></i> Login with Facebook
                                    </a>
                                </form>
                                <hr>
                                <div class="text-center">
                                    <a class="small" href="{% url 'users:forgot_password_url' %}">
                                      Forgot Password?
                                    </a>
                                </div>
                                <div class="text-center">
                                    <a class="small" href="{% url 'users:register_url' %}">  Create an Account!
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block js_body %}
  <script type="text/javascript">
      $(document).ready(function() {
          $('.login-top-right-link').addClass('active-nav-link-x')
      })
  </script>
{% endblock %}

src/ui/templates/theme/register.html
{% extends 'base_x.html' %}
{% load static %}

{% block title %} Register {% endblock %}

{% block container %}
<div class="container">
    <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
                <!--
                    <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
                -->
                <div class="col-lg-8 offset-lg-2">
                    <div class="p-5">
                        <div class="text-center">
                            <h1 class="h4 text-gray-900 mb-4">Create An Account!</h1>
                        </div>
                        <form class="user">
                            <div class="form-group row">
                                <div class="col-sm-6 mb-3 mb-sm-0">
                                    <label for="first_name">First name</label>
                                    <input type="text" class="form-control form-control-user" id="first_name" placeholder="First Name" value="Wes">
                                </div>
                                <div class="col-sm-6">
                                    <label for="last_name">Last name</label>
                                    <input type="text" class="form-control form-control-user" id="last_name" placeholder="Last Name" value="McKinney">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="email">Email</label>
                                <input type="email" class="form-control form-control-user" id="email" placeholder="Email Address" value="wes@gmail.com">
                            </div>
                            <div class="form-group row">
                                <div class="col-sm-6 mb-3 mb-sm-0">
                                    <label for="password">Password</label>
                                    <input type="password" class="form-control form-control-user" id="password" placeholder="Password" value="Wes@123">
                                </div>
                                <div class="col-sm-6">
                                    <label for="conf_password">Confirm Password</label>
                                    <input type="password" class="form-control form-control-user" id="conf_password" placeholder="Repeat Password" value="Wes@123">
                                </div>
                            </div>
                            <a href="{% url 'users:login_url' %}" class="btn btn-primary btn-user btn-block">
                            Register Account
                            </a>
                            <hr>
                            <a href="{% url 'index_url' %}" class="btn btn-google btn-user btn-block">
                              <i class="fab fa-google fa-fw"></i> Register with Google
                            </a>
                            <a href="{% url 'index_url' %}" class="btn btn-facebook btn-user btn-block">
                              <i class="fab fa-facebook-f fa-fw"></i> Register with Facebook
                            </a>
                        </form>
                        <hr>
                        <div class="text-center">
                            <a class="small" href="{% url 'users:forgot_password_url' %}">Forgot Password?</a>
                        </div>
                        <div class="text-center">
                            <a class="small" href="{% url 'users:login_url' %}">Already have an account? Login!</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block js_body %}
  <script type="text/javascript">
      $(document).ready(function() {
          $('.register-top-right-link').addClass('active-nav-link-x')
      })
  </script>
{% endblock %}

src/ui/templates/users/dashboard.html
<!--Write your own-->

src/ui/templates/users/forgot_password.html
<!--Write your own-->

src/ui/templates/users/login.html
<!--Write your own-->

src/ui/templates/users/signup.html
<!--Write your own-->